### ISSUE TITLE
Is it possible to implement TableProvider for a struct that owns the font data

### ISSUE THREAD

**Issue by LaurenzV** [googlefonts/fontations#1027]
I'm basically trying to build a version of `FontRef` that, instead of being backed by a slice of data, owns the data via `Arc`. It looks something like this:

```rs
pub struct Repr {
    data: Arc<Vec<u8>>,
    records: BTreeMap<Tag, (usize, usize)>
}

pub struct Font(Arc<Repr>);

impl Font {
    pub fn new(data: Arc<Vec<u8>>) -> Option<Self> {
        let mut records = BTreeMap::new();
        let font_data = FontData::new(data.as_slice());
        let table_directory = TableDirectory::read(font_data).ok()?;

        for record in table_directory.table_records() {
            let start = Offset32::new(record.offset()).non_null()?;
            let len = record.length() as usize;
            records.insert(record.tag.get(), (start, start + len));
        }

        Some(Self(Arc::new(Repr {
            data,
            records
        })))
    }
}

impl<'a> TableProvider<'a> for Font {
    fn data_for_tag(&self, tag: Tag) -> Option<FontData<'a>> {
        let (start, end) = self.0.records.get(&tag)?;
        Some(FontData::new(self.0.data.as_slice().get(*start..*end)?))
    }
}
```

which however results in the following error:

```
error: lifetime may not live long enough
  --> src/font/mod.rs:78:9
   |
75 | impl<'a> TableProvider<'a> for Font {
   |      -- lifetime `'a` defined here
76 |     fn data_for_tag(&self, tag: Tag) -> Option<FontData<'a>> {
   |                     - let's call the lifetime of this reference `'1`
77 |         let (start, end) = self.0.records.get(&tag)?;
78 |         Some(FontData::new(self.0.data.as_slice().get(*start..*end)?))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method was supposed to return data with lifetime `'a` but it is returning data with lifetime `'1`
```

If I try to change it to `&'a self`, I get this instead:

```
error[E0308]: method not compatible with trait
  --> src/font/mod.rs:76:5
   |
76 |     fn data_for_tag(&'a self, tag: Tag) -> Option<FontData<'a>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
   |
   = note: expected signature `fn(&font::Font, skrifa::Tag) -> Option<_>`
              found signature `fn(&'a font::Font, skrifa::Tag) -> Option<_>`
note: the anonymous lifetime as defined here...
  --> src/font/mod.rs:76:5
   |
76 |     fn data_for_tag(&'a self, tag: Tag) -> Option<FontData<'a>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...does not necessarily outlive the lifetime `'a` as defined here
  --> src/font/mod.rs:75:6
   |
75 | impl<'a> TableProvider<'a> for Font {
   |      ^^
```

Is there something obvious I'm missing here (I'm not super knowledgeable about lifetimes unfortunately) to achieve what I want, or is it simply not (intended to be?) possible, without resorting to `unsafe` to pass a static lifetime?

**Comment by cmyr** [comment]
so this is something I've played around with and haven't really figured out a satisfactory design for.

In your version, the reason it doesn't work is because the `'a` bound is explicitly _not_ a bound on self, but instead on the underlying data. There's no way that I know of, given the current trait signature, to express the constraint that `'a` is the lifetime of `&self`. :(

**Comment by LaurenzV** [comment]
Ah okay, that's too bad. :( But thanks!

The reason is that I want to have a wrapper struct around a `FontRef`, and this struct is used in a somewhat deeply nested chain of structs, meaning that if I require a lifetime bound on this one struct it requires lifetime bounds on all parent structs, which I would kind of like to avoid... The only other way I see is to just store the raw data in the struct and reparse it into a FontRef everytime I want to get something from the font, but this obviously wouldn't be great performance-wise... But I'm sure I will find an alternative approach. 😄

**Comment by dfrg** [comment]
For a while now, I've been considering removing the `TableProvider` trait due to the complications raised here and the fact that it prevents a lot of potential size optimizations in `skrifa` where we have to store a slice or other large structure when an offset might suffice.

The original motivation was to support cases where something like a font editor had a set of individual tables but not a complete assembled font. The current trait could handle that but notably would not allow generation of tables on demand without unsafe. I'm not sure the trade off is worth it.

For this particular case, you would need to add another layer of indirection:

```rust
impl Font {
    pub fn tables(&self) -> FontTables {
        FontTables(self)
    }
}

pub struct FontTables<'a>(&'a Font);

impl<'a> TableProvider<'a> for FontTables<'a> {
    fn data_for_tag(&self, tag: Tag) -> Option<FontData<'a>> {
        let (start, end) = self.0.0.records.get(&tag)?;
        Some(FontData::new(self.0.0.data.as_slice().get(*start..*end)?))
    }
}
```

But I'm not sure the `BTreeMap` buys much in terms of performance. Would love to see measurements.
