### ISSUE TITLE
Allow specifying additional derived traits in codegen

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#186]
It would be nice to be able to say, for instance, that you would like to derive `Hash` or `PartialOrd` for some record. We could then be somewhat judicious about this, since not all traits *can* be implemented for all types, and not all traits may be desirable for all types.

**Comment by rsheeter** [comment]
+1. IMHO marking types you are likely to want to hash or compare is valid beyond Rust. For example, both Java or Python dataclasses based versions might benefit. That it's done by derive macro is a Rust-specific implementation detail.

**Comment by rsheeter** [comment]
For example, https://github.com/googlefonts/fontations/issues/157#issuecomment-1356834384 (linking to comment rather than content to create the issue relationship) shows one Java implementation. Hints to which types benefit from equals and hashCode would definitely help if we generated a more complete version.
