### ISSUE TITLE
improve otexplorer experience

### ISSUE THREAD

**Issue by Colerar** [googlefonts/fontations#573]
Currently, the experience of `otexplorer` is really awful, for example:

```
❯ otexplorer --help
Error: Error("args\n  Generate font table representations\n\nARGS:\n    <input>\n\nOPTIONS:\n    -i, --index <index>\n\n    -l, --list\n\n    -q, --query <query>\n\n    -t, --tables <include>\n\n    -x, --exclude <exclude>\n\n    -h, --help\n      Prints help information.\n")
```

The error type for `main` is really confusing:

https://github.com/googlefonts/fontations/blob/6bcc4ca4f09d525c591a0b089312c7ab94545e3e/otexplorer/src/main.rs#L177

Generally speaking, executable crates can use [anyhow](https://github.com/dtolnay/anyhow) for unified error handling, and manually implementing a String-based Error is very unreasonable and difficult to maintain.

And the crate `xflags` for underlying options parsing seems no longer actively developed since 2022. Probably it's best to migrate to certain more mature and popular crate like [Clap](https://github.com/clap-rs/clap) for better user experience.

I can create a PR for this if you want. :)

**Comment by cmyr** [comment]
Thanks! I hadn't noticed that I'd broken the help message since I've never needed to use it, and the main documentation for otexplorer was in its readme.

otexplorer is in a funny position: it was originally intended as a way to check that our parsing code was sane during the initial development of read-fonts, and it is sort of broken in certain cases (basically it does not provide a useful representation of any data that is stored in a way that requires manual processing, such as entries in the `glyf` table, or encoded varation data) but I *do* find it helpful as a way to inspect the raw bytes of tables during debugging, and so I'm hesitant to rip it out completely. That said, I do not currently have plans to work on improving it much.

I opened #574 to at least make the `--help` flag print something useful.


on `xflags`: the rationale here is that it is much smaller and faster to compile than `clap`, and so I prefer it for simple tools. If at some point otexplorer became significantly more complicated I would definitely consider migrating. :)
