### ISSUE TITLE
BigEndian in codegen feels like noise

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#71]
Since everything is BigEndian having to spell it out in codegen is just noise. Perhaps we could use the types from https://learn.microsoft.com/en-us/typography/opentype/spec/otff#data-types and no BigEndian wrapper in the input?

**Comment by rsheeter** [comment]
I'm happy to attempt to implement if we do decide to go that way. If we can use the spec types instead of Rust types that moves codegen inputs toward being a potentially reusable schema.

**Comment by rsheeter** [comment]
Looks like we already use some non-Rust-native "types" in codegen inputs. For example, I see Uint24 in cmap.

**Comment by cmyr** [comment]
I've thought about this a bit, so let me try and share my thoughts:

- I agree it would be nice if we could get rid of `BigEndian`, in general.
- codegen needs to know which types are scalars, and which types are not.
- for types that are scalars, we need to have two forms: the 'raw' form and the 'cooked' form.
- we would like to avoid as much as possible 'magic' types, e.g. types where the behaviour of codegen depends on the specific name of a type.
- we would like codegen to be able to define new scalar types, such as in the case of bitflags or enums.
- we would like to be able to define *custom* scalar types in our own code, as needed; for instance it would be nice to have a type for [`LookupFlag`](https://learn.microsoft.com/en-us/typography/opentype/spec/chapter2#lookupFlag), which is a byte of flags beside a byte that's a u8


The nice thing that the `BigEndian<T>` pattern gives us is we always know both the raw type (`BigEndian<T>`) and the cooked type, without us needing any additional information.

As an example of why this is nice, let's take the following fictionalized codegen input:

```rust
flags u16 ValueFlags {
    X_PLACEMENT = 0x0001,
    Y_PLACEMENT = 0x0002,
    // etc
}

table MyTable {
    flags: BigEndian<ValueFlags>,
}

record MyRecord {
    flags: BigEndian<ValueFlags>,
}
```

Part of the code that we generate in this case is,

```rust
pub struct MyRecord {
    pub flags: BigEndian<ValueFlags>,
}

impl<'a> MyTable<'a> {
    pub fn flags(&self) -> ValueFlags { .. }
}
```

The point here is that `MyRecord` needs to know the raw type, but `MyTable` needs to know the cooked type.

What would the alternatives be?

One option would be to have a *convention*, where we assume that all scalar types have a raw version that follows some naming convention, like always prepending `Raw`. If codegen was creating a new scalar type `ValueFlags` it would also create `RawValueFlags`, and a custom scalar type would be expected to do the same.

But how do we know which types are scalars?

For instance, imagine the following (omitting count annotations for brevity)

```rust
table MyTable {
    value_array: [BigEndian<ValueFlags>],
    records_array: [SomeRecord],
}
```

Here `ValueFlags` is a scalar, and `SomeRecord` is a record. Currently, we generate the following getters:

```rust
impl MyTable {
    fn value_array(&self) -> &[BigEndian<ValueFlags>];
    fn records_array(&self) -> &[SomeRecord];
}
```

Now imagine instead that we've gotten rid of `BigEndian`. Our input looks like this:

```rust
table MyTable {
    value_array: [ValueFlags],
    records_array: [SomeRecord],
}
```

and we want our getters to look like:

```rust
impl MyTable {
    fn value_array(&self) -> &[RawValueFlags];
    fn records_array(&self) -> &[SomeRecord];
}
```

Specifically: we need to use the *raw* version of `ValueFlags` in the getter, but this is not necessary for `SomeRecord`.

How does the codegen tool know that `ValueFlags` and `SomeRecord` need to be treated differently?

I do not have a satisfactory answer to this question; that is, I do not have an answer that does not ultimately lead to more complexity and require more inscrutable hacks.

There are compromises: for instance we could not require `BigEndian` for the basic types in the spec, but keep it around for custom types. Maybe this is an improvement? It would certainly simplify writing the inputs, but it would not remove any overall complexity since `BigEndian` would stick around.

**Comment by rsheeter** [comment]
> how do we know which types are scalars?

Can we figure that out in a non-hacky (principled if you wish) manner, specifically by introducing a simple analysis phase? Does something prevent us from learning from the input that ValueFlags and SomeRecord have certain characteristics and using that information during codegen?

1. Read the raw input into some other representation we will use in subsequent steps (we do this step already)
1. Semantic analysis (new phase!)
   * Wander around the output of the prior step and do things like figure out the nature of "types"
   * Types from https://learn.microsoft.com/en-us/typography/opentype/spec/otff#data-types are built-in (imho we should stop using Rust types in codegen input, spell u32 as uint32 to match spec, etc)
   * Here we discover and remember what ValueFlags means
   * Output of this phase is a model that is friendly to the next phase
1. Write code
